logging:
  level:
    root: info

spring:
  application:
    name: api-gateway
  
  config:
    import: optional:configserver:http://localhost:9092
  profiles:
    active:
  cloud:
    gateway:
      default-filters:
      - JwtAuthenticationFilter

server:
  port: 9091
